#zsh prompt theme
brew "pure" # https://github.com/sindresorhus/pure#getting-started
brew "zsh-syntax-highlighting" # https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md
brew "shellcheck"
