brew "neovim"

# Shell & Terminal Tools
brew "pure" # https://github.com/sindresorhus/pure#getting-started
brew "zsh-syntax-highlighting" # https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md
brew "shellcheck"
brew "hyperfine"

# Terminal & System Applications
cask "ghostty"
cask "hex-fiend"
cask "grandperspective"

# Development Tools
brew "insomnia"
brew "pusher"

# Media & Productivity
cask "typora"
brew "xld"
cask "spotify"
