# Shell & Terminal Tools
brew "pure" # https://github.com/sindresorhus/pure#getting-started
brew "zsh-syntax-highlighting" # https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md
brew "shellcheck"

# Terminal & System Tools
brew "ghostty"
brew "raycast"
brew "hex-fiend"
brew "grandperspective"

# Development Tools
brew "insomnia"  # API testing

# Media & Productivity
brew "typora"
brew "xld"  # Audio converter
